# Generated by Django 4.0.4 on 2022-06-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint',
            fields=[
                # ('appointname', models.AutoField(primary_key=True, serialize=False)),
                ('appointemail', models.CharField(default='', max_length=150)),
                ('appointtime', models.CharField(default='', max_length=150)),
                ('appointdate', models.CharField(default='', max_length=150)),
                ('appointmentfor', models.CharField(default='', max_length=150)),
            ],
        ),
        # migrations.AlterField(
        #     model_name='contact',
        #     name='city',
        #     field=models.CharField(default='', max_length=100),
        # ),
    ]
