# Generated by Django 4.0.4 on 2022-06-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_contact_city'),
        ('authenticate', '0003_appoint_alter_contact_city'),
    ]

    operations = [
    ]
