# Generated by Django 4.0.4 on 2022-06-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_merge_20220608_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
